b=read_ascii('bayesError.dat')
d2=b.(0)

;np=n_elements(d2[*,0])
ns=n_elements(d2)
x=findgen(ns)

psopen, 'bayesError', /encapsulated
standard, xsize=15,ysize=12
;xlab=textoidl('log MCMC samples')
;plot,alog10(x),d2,xtitle=xlab,ytitle='Cumulated relative errors',xstyle=1
xlab=textoidl('MCMC samples')
plot,x,d2,xtitle=xlab,ytitle='Cumulated relative errors',xstyle=1
psclose

