#!/bin/bash
echo "Starting Double test"

cd src/
make -f Makefile.intel clean
make -f Makefile.intel
make -f Makefile.GPU.intel

cd ../Benchmarks/GridGradientBenchmark
make -f Makefile.GPU clean
make -f Makefile.GPU
#./ChiBenchmark_GPU ../ConfigFiles/90PotSIS.par T
./ChiBenchmark_GPU ../ConfigFiles/MarkusBenchmark.par T
#./ChiBenchmark_GPU ../ConfigFiles/MarkusBenchmark1SIS.par T

#cd ../Benchmarks/GradientBenchmark
#make -f Makefile clean
#make -f MakefileDouble
#./GradientBenchmark 

echo "Finish Double test"
