#!/bin/bash
echo "Starting Float test"

cd src/
make -f Makefile.intel clean
make -f MakefileFloat.intel
make -f MakefileFloat.GPU.intel

cd ../Benchmarks/GridGradientBenchmark
make -f Makefile.GPU clean
make -f MakefileFloat.GPU
#./ChiBenchmark_GPU ../ConfigFiles/90PotSIS.par T
./ChiBenchmark_GPU ../ConfigFiles/MarkusBenchmark.par T
#./ChiBenchmark_GPU ../ConfigFiles/MarkusBenchmark1SIS.par T

echo "Finish Float test"
